$ANSIBLE_VAULT;1.1;AES256
64613330323130666665323730393833663766363762303962346532323666633332306137646439
6537316661343038393636333265313564333662663061620a656532363238663065336163636230
35353139363331653463333630666665653961633030613361303961613233666335636662323263
3337633338303534390a363738373831313638383934333639363834363562623436353865626561
36383063333261313536383639396566303366343534326134343431643531363239643761393037
62643731336432373238366436313838646232336633323033623337653763386165666566346239
66343166376234666631386635636137396164303636343463663331396136616132613939333631
37333033366163336661346434393938656164613963306562646230653932313031313731393937
35376339336232353964356163366463323234633361373464633239643037386530383238636133
66643239643232323536343737613537306333373335373366396462633662353763386531383738
34653230666561363934373365376531613131643339663839306237316362363566666533653265
66313664353661613535663838313865393166346331613938363465333430633532383134323135
31303634656530656536633664366165306233336630363066393434626465303939333065656337
32383762346637313137363235343861303337653636383861323732376332303339323061303263
32636135393732333135663439346434333439343438386432363365636461363032356138633935
64396665616165346434366464373130383730626166626133616464353134616332336365643361
32303566343562333861393866633734383561333464613535353935343336303930383535613833
38333637616264316530323266343763663361363461633233373261393230383962356439613433
38653634643238646366666532383561303137613666393435616239306565326561646164313539
38343161616564353463393933626330626534353236636131396132393734356233393131323636
62643137396363376232346663313962386437393463386265376463313062636261353134353338
62363339643638343864623339616533623565363464356332326136323763346333666365623439
63643039336261643165356636326238393265326338396637323839323461653138303165343566
61633563623839383665
