$ANSIBLE_VAULT;1.1;AES256
30353231363562336330636138626561643230376636303766316463306461623230386666613737
6165373438366438623634643162363136666634363135330a353332656563623861663563306439
31656631636334343034363033323163653030656335636534373632656435303265613136346365
6261646636663963360a633339613363363462346337393533323763346430363130316430326166
61383936333736376661663931653263343466356661306666353031343132333632396565346164
63393062616330636633653135653064646565643534303730653438303464363331326238626666
65616435333061366265303465353336353032636236346632626538363266363163326534633866
65646562363662343137306432393130316566616431323061646136323565636632613038353966
3938
